# Generated by Django 5.2.6 on 2025-09-26 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionaries', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('fid', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='사건 FID')),
            ],
            options={
                'verbose_name': '사건 파일',
                'verbose_name_plural': '사건 파일 목록',
                'ordering': ['fid'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ids', models.CharField(blank=True, max_length=255, null=True, verbose_name='IDS')),
                ('fnames', models.TextField(blank=True, null=True, verbose_name='파일 이름')),
                ('disease_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='질병 코드')),
                ('job_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='직종 코드')),
                ('decision', models.TextField(blank=True, max_length=100, null=True, verbose_name='결정 사항')),
                ('smry', models.TextField(blank=True, null=True, verbose_name='고찰')),
                ('pdf_link', models.URLField(blank=True, max_length=1024, null=True, verbose_name='PDF 링크')),
                ('exp_start', models.IntegerField(blank=True, null=True, verbose_name='노출 시작 연도')),
                ('exp_period', models.IntegerField(blank=True, null=True, verbose_name='노출 기간(년)')),
                ('process_link', models.URLField(blank=True, max_length=1024, null=True, verbose_name='공정 링크')),
                ('pop_link', models.URLField(blank=True, max_length=1024, null=True, verbose_name='인구 링크')),
                ('original_ids', models.CharField(blank=True, max_length=255, null=True, verbose_name='최초 IDS')),
                ('original_disease_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='최초 질병명')),
                ('original_disease_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='최초 질병 코드')),
                ('original_job', models.CharField(blank=True, max_length=255, null=True, verbose_name='최초 직종')),
                ('original_job_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='최초 직종 코드')),
                ('original_decision', models.TextField(blank=True, max_length=1000, null=True, verbose_name='최초 결정 사항')),
                ('original_smry', models.TextField(blank=True, null=True, verbose_name='최초 고찰')),
                ('original_exposure', models.TextField(blank=True, max_length=255, null=True, verbose_name='최초 유해인자')),
                ('original_pdf_link', models.URLField(blank=True, max_length=2048, null=True, verbose_name='최초 PDF 링크')),
                ('original_exp_start', models.IntegerField(blank=True, null=True, verbose_name='최초 노출 시작 연도')),
                ('original_exp_period', models.IntegerField(blank=True, null=True, verbose_name='최초 노출 기간(년)')),
                ('original_process_link', models.URLField(blank=True, max_length=2048, null=True, verbose_name='최초 공정 링크')),
                ('original_pop_link', models.URLField(blank=True, max_length=2048, null=True, verbose_name='최초 인구 링크')),
                ('disease_confirmed', models.BooleanField(default=False, verbose_name='질병확인')),
                ('job_confirmed', models.BooleanField(default=False, verbose_name='직종확인')),
                ('exposure_confirmed', models.BooleanField(default=False, verbose_name='유해인자확인')),
                ('decision_confirmed', models.BooleanField(default=False, verbose_name='결정확인')),
                ('smry_confirmed', models.BooleanField(default=False, verbose_name='고찰확인')),
                ('changed_fields', models.TextField(blank=True, null=True, verbose_name='변경된 항목')),
                ('last_modified_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_records', to='records.case', verbose_name='사건 파일')),
                ('disease', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.diseasedictionaryentry', verbose_name='표준 질병')),
                ('exposure', models.ManyToManyField(blank=True, to='dictionaries.exposuredictionary', verbose_name='표준 유해인자')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dictionaries.jobcodeoccupation', verbose_name='표준 직종')),
                ('last_modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='수정한 사람')),
            ],
            options={
                'verbose_name': '질병 기록',
                'verbose_name_plural': '질병 기록들',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='마지막 활동 시간')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PopulationData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=255, verbose_name='변수명')),
                ('value', models.TextField(verbose_name='값')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='population_data', to='records.case', verbose_name='사건 파일')),
            ],
            options={
                'verbose_name': '인구학적 정보',
                'verbose_name_plural': '인구학적 정보 목록',
                'unique_together': {('case', 'variable')},
            },
        ),
        migrations.CreateModel(
            name='WorkProcessData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variable', models.CharField(max_length=255, verbose_name='변수명')),
                ('value', models.TextField(verbose_name='값')),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_processes', to='records.case', verbose_name='사건 파일')),
            ],
            options={
                'verbose_name': '작업 공정 정보',
                'verbose_name_plural': '작업 공정 정보 목록',
                'unique_together': {('case', 'variable')},
            },
        ),
    ]
