# Generated by Django 5.2.6 on 2025-09-28 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now_add=True, verbose_name='수정 시간')),
                ('changed_fields', models.TextField(blank=True, verbose_name='변경된 필드')),
                ('summary', models.CharField(blank=True, max_length=500, verbose_name='변경 요약')),
                ('before_values', models.JSONField(blank=True, default=dict, verbose_name='변경 전 값')),
                ('after_values', models.JSONField(blank=True, default=dict, verbose_name='변경 후 값')),
                ('modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='records.diseaserecord', verbose_name='질병 기록')),
            ],
            options={
                'verbose_name': '수정 이력',
                'verbose_name_plural': '수정 이력 목록',
                'ordering': ['-modified_at'],
            },
        ),
    ]
