# Generated by Django 5.2.6 on 2025-10-01 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_recordrevision'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaserecord',
            name='additional_disease_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='추가 질병 코드'),
        ),
        migrations.AddField(
            model_name='diseaserecord',
            name='additional_disease_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='추가 질병명'),
        ),
        migrations.AddField(
            model_name='diseaserecord',
            name='original_additional_disease_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='최초 추가 질병 코드'),
        ),
        migrations.AddField(
            model_name='diseaserecord',
            name='original_additional_disease_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='최초 추가 질병명'),
        ),
    ]
