# Generated by Django 5.2.6 on 2025-10-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_diseaserecord_additional_disease_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaserecord',
            name='discussion_notes',
            field=models.TextField(blank=True, null=True, verbose_name='논의 사항'),
        ),
    ]
