# Generated by Django 5.2.6 on 2025-10-06 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_diseaserecord_discussion_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='담당자 이름')),
                ('ids_from', models.IntegerField(verbose_name='IDS 시작 번호')),
                ('ids_to', models.IntegerField(verbose_name='IDS 끝 번호')),
                ('color', models.CharField(default='#2196F3', max_length=7, verbose_name='담당자 색상')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='연결된 사용자')),
            ],
            options={
                'verbose_name': '담당자',
                'verbose_name_plural': '담당자 목록',
                'ordering': ['ids_from'],
            },
        ),
    ]
