# Generated by Django 5.2.4 on 2025-09-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseDictionaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='질병명')),
                ('disease_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='질병코드')),
            ],
            options={
                'verbose_name': '질병 사전',
                'verbose_name_plural': '질병 사전',
                'ordering': ['disease_name'],
            },
        ),
        migrations.CreateModel(
            name='ExposureDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='유해인자명')),
            ],
            options={
                'verbose_name': '유해인자 사전',
                'verbose_name_plural': '유해인자 사전',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobCodeOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_code', models.CharField(max_length=10, unique=True, verbose_name='직종 코드')),
                ('occupation', models.CharField(max_length=255, verbose_name='직종명')),
            ],
            options={
                'verbose_name': '직종 코드-직종명 사전',
                'verbose_name_plural': '직종 코드-직종명 사전',
                'ordering': ['occupation'],
            },
        ),
    ]
