# Generated by Django 5.2.6 on 2025-10-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionaries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diseasedictionaryentry',
            name='disease_code',
            field=models.CharField(db_index=True, default='', max_length=255, unique=True, verbose_name='질병코드'),
        ),
        migrations.AlterField(
            model_name='diseasedictionaryentry',
            name='disease_name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='질병명'),
        ),
    ]
